name: Nix CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')" # respects [skip-ci]
    strategy:
        matrix:
            ghc:
                - "ghc883"
                - "ghc8101"  

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        submodules: recursive

    - uses: cachix/install-nix-action@v10
      name: Setup Nix
      with:
        skip_adding_nixpkgs_channel: true # we don't need a nixpkgs channel because we're pinning with Niv anyways!

    - name: Build
      run: |
        nix-build --argstr compiler "${{ matrix.ghc }}" --attr lily default.nix  
